ARG BASE_IMAGE=nvidia/cudagl:10.0-devel-ubuntu18.04
FROM $BASE_IMAGE

RUN apt-get update
RUN apt-get install \
	git \ 
	libglu1-mesa-dev \
	pulseaudio \
	python3 \
	python3-pip \
	sudo \
	sudo \
	wget \ 
	x11-xserver-utils \
	xdg-user-dirs \
	unzip \
	-y --no-install-recommends

RUN pip3 install setuptools wheel
# RUN pip3 install airsimneurips

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \ 
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \ 
	adduser airsim_user sudo && \ 
	adduser airsim_user audio && \ 
	adduser airsim_user video

USER airsim_user
ENV USER airsim_user
WORKDIR /home/airsim_user
RUN sudo chown -R airsim_user /home/airsim_user

RUN wget -c https://github.com/Hadisalman/AirSim/releases/download/v0.1-alpha/RobustnessNeighborhood.zip && \
	mkdir -p /home/$USER/Documents/AirSim && \
	unzip RobustnessNeighborhood.zip && \
	git clone https://github.com/Hadisalman/AirSim.git
	# mv RobustnessNeighborhood/ ../ && \
	# cd ../

ENV PATH /opt/conda/bin:$PATH

# RUN apt-get update --fix-missing && \
#     apt-get install -y wget bzip2 ca-certificates curl git && \
#     apt-get clean
	
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.8.3-Linux-x86_64.sh -O ~/miniconda.sh && \
    sudo /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    sudo /opt/conda/bin/conda clean -tipsy && \
    sudo ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc

ENV PATH /opt/conda/bin:$PATH
ENV LD_LIBRARY_PATH /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH

RUN cd AirSim && git checkout 4.24 && cd ../ && \
	pip3 install AirSim/PythonClient && \
	# pip3 install torch torchvision
	conda install pytorch torchvision cudatoolkit=10.1 -c pytorch


# git clone https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing && \
# 	cd AirSim-NeurIPS2019-Drone-Racing && \
# 	bash download_training_binaries.sh && \
# 	bash download_qualification_binaries.sh && \
# 	mv AirSim_Training/ ../ && \
# 	mv AirSim_Qualification/ ../ && \
# 	cd ../
	
# RUN git clone https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing && \
# 	cd AirSim-NeurIPS2019-Drone-Racing && \
# 	bash download_training_binaries.sh && \
# 	bash download_qualification_binaries.sh && \
# 	mv AirSim_Training/ ../ && \
# 	mv AirSim_Qualification/ ../ && \
# 	cd ../